### PR TITLE
Feat: Link now changes src of iframe

### PR DESCRIPTION
**Pull request by zoef-yt**
Updated js to change the source of iframe depending on the `#` at the end of the URL this will help to open the exact components description page from the readme.

### CODE REVIEW

**Comment by Muzammil-khan710** [comment]
Good to merge ! Zoef

**Review by Muzammil-khan710 — APPROVED** [review]
Good to merge ! Zoef

**Review by purvasharmadev — APPROVED** [review]

**Review by zoyatanweer — APPROVED** [review]
nice update to the code, good to merge.

**Review by ritu9898 — APPROVED** [review]

**Comment by ritu9898** [comment]
Looks good to merge

**Pull request merged**
