### PR TITLE
Style: Changed the style of scrollbar and footer.

### PR DESCRIPTION
**Pull request by zoef-yt**
Style: Changed the style of scrollbar and footer.
Feat: added new list time for more components.

### CODE REVIEW

**Review by itsmebipul00 — APPROVED** [review]

**Review by varun13169 — APPROVED** [review]

**Review by developer-anand — APPROVED** [review]
Great Work Man.

**Review by Omkar-Ghate — APPROVED** [review]
Looks awesome! The transitions are smooth. Great work.

**Review by iRohitGaur — APPROVED** [review]
Looks great! Good to merge 👍🏻

**Comment by zoef-yt** [comment]
Thanks all for approving.

**Pull request merged**
