### PR TITLE
feat: Added text-utilities to Component library

### PR DESCRIPTION
**Pull request by zoef-yt**
Feat: Added text utilities to my component library 
image
image
image

### CODE REVIEW

**Review by amartya-rs — APPROVED** [review]
Looks good to me.

**Review by Omkar-Ghate — APPROVED** [review]
Great work. Good to merge.

**Review by srishtigautam21 — APPROVED** [review]
good work zoef ...good to merge

**Review by iRohitGaur — APPROVED** [review]
Looks great! Good to merge 👍🏻

**Comment by zoef-yt** [comment]
Thanks for approving the pr

**Pull request merged**
