### PR TITLE
Feat: Added toast to my CL.

### PR DESCRIPTION
**Pull request by zoef-yt**
Added toast to my CL

https://user-images.githubusercontent.com/67889207/154839988-77e1cee4-f4d7-4019-b85c-741c69722f3c.mp4

.

### CODE REVIEW

**Review by sach10-create — APPROVED** [review]
Rest code looks clean

**Review by saurabhan — APPROVED** [review]
Looks great, the code is clean and readable. approved

**Review by Omkar-Ghate — APPROVED** [review]
Neat and clean UI. Looks good to merge.

**Review by j24m — APPROVED** [review]
Hello, 5/5 stars for small PR :p , btw I can't find anything in the code that needs changes, infact code looks as good as the UI. Great work, keep it up  :)

**Pull request merged**
